spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true # print sql statements to console
#    properties:
#      hibernate:
#        format_sql: true